# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20150308_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='summary',
            field=models.CharField(default=b'SOME STRING', max_length=128),
        ),
    ]
